name = "mon-app-repas"
compatibility_date = "2024-04-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build"

# === ENVIRONNEMENT PAR DÉFAUT ===
# Utilisé en local ou si tu n'as pas précisé --env
# D1 databases have been removed as we've migrated to Neon PostgreSQL
# Environment variables for Neon are set in .env for local development

# Configuration pour Cloudflare Access
[vars]
AUTH_ENABLED = "true"
ENVIRONMENT = "dev"
# Variables pour la connexion à la base de données Neon
# Ces variables seront remplacées par celles définies dans .dev.vars
NEON_DEV_URL = ""
NEON_PREPROD_URL = ""
NEON_PROD_URL = ""
NEON_PASSWORD = ""
# Clerk Authentication - Ces clés seront définies dans .dev.vars pour le développement
# et comme secrets dans le dashboard Cloudflare pour la production
CLERK_PUBLISHABLE_KEY = ""
CLERK_SECRET_KEY = ""
# Variables pour le proxy Clerk (Cloudflare Function)
CLERK_PROXY_URL = "https://organisersejour.pages.dev/api/clerk"
CLERK_FAPI = "https://frontend-api.clerk.dev"

# === ENVIRONNEMENT PREVIEW (PRÉPROD) ===
[env.preview]
vars = { ENVIRONMENT = "preprod", AUTH_ENABLED = "true" }
compatibility_flags = ["nodejs_compat"] # Ajouté ici

# D1 databases have been removed as we've migrated to Neon PostgreSQL
# Neon database URLs are set as secrets in the Cloudflare dashboard

# === ENVIRONNEMENT PRODUCTION ===
[env.production]
vars = { ENVIRONMENT = "prod", AUTH_ENABLED = "true" }
compatibility_flags = ["nodejs_compat"] # Ajouté ici

# D1 databases have been removed as we've migrated to Neon PostgreSQL
# Neon database URLs are set as secrets in the Cloudflare dashboard
