name = "mon-app-repas"
compatibility_date = "2024-04-12"

pages_build_output_dir = "./build"

[[d1_databases]]
binding = "DB"               # Le nom utilisé dans le code
database_name = "hello-db"   # Le nom que tu as donné
database_id = "96804f33-7c7f-4bfd-a532-a1e7c743728e"  # Tu peux obtenir l'ID avec: `npx wrangler d1 list`

[[d1_databases]]
binding = "DB_PREPROD"  # Un autre nom utilisé pour la préprod
database_name = "hello-db-preprod"
database_id = "68a63f61-c3d3-46c1-a2f7-a907e6c5472c"


# === ENVIRONNEMENT PREVIEW (Pages preview sur un sous-domaine) ===
[env.preview]
vars = { ENVIRONMENT = "preprod" }

[[env.preview.d1_databases]]
binding = "DB_PREPROD"
database_name = "hello-db-preprod"
database_id = "68a63f61-c3d3-46c1-a2f7-a907e6c5472c"


# === ENVIRONNEMENT PRODUCTION ===
[env.production]
vars = { ENVIRONMENT = "prod" }

[[env.production.d1_databases]]
binding = "DB_PROD"
database_name = "hello-db"
database_id = "96804f33-7c7f-4bfd-a532-a1e7c743728e"

