name = "mon-app-repas"
compatibility_date = "2024-04-12"
pages_build_output_dir = "./build"

# === ENVIRONNEMENT PAR DÉFAUT ===
# Utilisé en local ou si tu n’as pas précisé --env
[[d1_databases]]
binding = "DB"
database_name = "hello-db"
database_id = "96804f33-7c7f-4bfd-a532-a1e7c743728e"

[[d1_databases]]
binding = "DB_PREPROD"
database_name = "hello-db-preprod"
database_id = "68a63f61-c3d3-46c1-a2f7-a907e6c5472c"

# === ENVIRONNEMENT PREVIEW (PRÉPROD) ===
[env.preview]
vars = { ENVIRONMENT = "preprod" }

[[env.preview.d1_databases]]
binding = "DB_PREPROD"
database_name = "hello-db-preprod"
database_id = "68a63f61-c3d3-46c1-a2f7-a907e6c5472c"

# === ENVIRONNEMENT PRODUCTION ===
[env.production]
vars = { ENVIRONMENT = "prod" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "hello-db"
database_id = "96804f33-7c7f-4bfd-a532-a1e7c743728e"
