-- Migration to populate French names for autumn/winter ingredients and common ingredients (Part 2)

-- 5. Populate French names for autumn ingredients
UPDATE ingredients SET french_name = 'Citrouille' WHERE name = 'Pumpkin' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Courge butternut' WHERE name = 'Butternut squash' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Patate douce' WHERE name = 'Sweet potato' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Choux de Bruxelles' WHERE name = 'Brussels sprouts' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Chou-fleur' WHERE name = 'Cauliflower' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Brocoli' WHERE name = 'Broccoli' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Céleri-rave' WHERE name = 'Celery root' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Navet' WHERE name = 'Turnip' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Pomme' WHERE name = 'Apple' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Poire' WHERE name = 'Pear' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Raisin' WHERE name = 'Grape' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Prune' WHERE name = 'Plum' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Coing' WHERE name = 'Quince' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Canneberge' WHERE name = 'Cranberry' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Girolle' WHERE name = 'Chanterelle' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Cèpe' WHERE name = 'Porcini' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Shiitake' WHERE name = 'Shiitake' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Pleurote' WHERE name = 'Oyster mushroom' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Chevreuil' WHERE name = 'Venison' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Sanglier' WHERE name = 'Wild boar' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Faisan' WHERE name = 'Pheasant' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Châtaignes' WHERE name = 'Chestnuts' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Noix' WHERE name = 'Walnuts' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Noisettes' WHERE name = 'Hazelnuts' AND user_id = 'system';

-- 6. Populate French names for winter ingredients
UPDATE ingredients SET french_name = 'Chou frisé' WHERE name = 'Kale' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Chou' WHERE name = 'Cabbage' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Poireau' WHERE name = 'Leek' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Panais' WHERE name = 'Parsnip' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Courge d''hiver' WHERE name = 'Winter squash' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Rutabaga' WHERE name = 'Rutabaga' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Topinambour' WHERE name = 'Jerusalem artichoke' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Orange' WHERE name = 'Orange' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Clémentine' WHERE name = 'Clementine' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Pamplemousse' WHERE name = 'Grapefruit' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Grenade' WHERE name = 'Pomegranate' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Kaki' WHERE name = 'Persimmon' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Canard' WHERE name = 'Duck' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Bœuf à mijoter' WHERE name = 'Beef for stew' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Épaule de porc' WHERE name = 'Pork shoulder' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Haricots secs' WHERE name = 'Dried beans' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Lentilles' WHERE name = 'Lentils' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Orge perlé' WHERE name = 'Pearl barley' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Champignons séchés' WHERE name = 'Dried mushrooms' AND user_id = 'system';

-- 7. Populate French names for common ingredients
UPDATE ingredients SET french_name = 'Huile d''olive' WHERE name = 'Olive oil' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Huile végétale' WHERE name = 'Vegetable oil' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Beurre' WHERE name = 'Butter' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Sel' WHERE name = 'Salt' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Poivre noir' WHERE name = 'Black pepper' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Farine' WHERE name = 'Flour' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Sucre' WHERE name = 'Sugar' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Sucre brun' WHERE name = 'Brown sugar' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Miel' WHERE name = 'Honey' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Sirop d''érable' WHERE name = 'Maple syrup' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Extrait de vanille' WHERE name = 'Vanilla extract' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Levure chimique' WHERE name = 'Baking powder' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Bicarbonate de soude' WHERE name = 'Baking soda' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Cannelle' WHERE name = 'Cinnamon' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Muscade' WHERE name = 'Nutmeg' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Cumin' WHERE name = 'Cumin' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Paprika' WHERE name = 'Paprika' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Ail' WHERE name = 'Garlic' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Oignon' WHERE name = 'Onion' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Carotte' WHERE name = 'Carrot' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Céleri' WHERE name = 'Celery' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Pomme de terre' WHERE name = 'Potato' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Riz' WHERE name = 'Rice' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Pâtes' WHERE name = 'Pasta' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Poulet' WHERE name = 'Chicken' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Bœuf' WHERE name = 'Beef' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Porc' WHERE name = 'Pork' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Lard' WHERE name = 'Bacon' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Œuf' WHERE name = 'Egg' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Lait' WHERE name = 'Milk' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Crème' WHERE name = 'Cream' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Yaourt' WHERE name = 'Yogurt' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Fromage' WHERE name = 'Cheese' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Parmesan' WHERE name = 'Parmesan' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Pain' WHERE name = 'Bread' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Bouillon de poulet' WHERE name = 'Chicken stock' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Bouillon de bœuf' WHERE name = 'Beef stock' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Bouillon de légumes' WHERE name = 'Vegetable stock' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Vin blanc' WHERE name = 'White wine' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Vin rouge' WHERE name = 'Red wine' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Citron' WHERE name = 'Lemon' AND user_id = 'system';
UPDATE ingredients SET french_name = 'Citron vert' WHERE name = 'Lime' AND user_id = 'system';