name: Migrate D1 Database

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Apply D1 Migrations

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Apply migrations to preprod DB
        if: github.ref == 'refs/heads/dev'
        run: wrangler d1 migrations apply hello-db-preprod --remote
        working-directory: frontend
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Apply migrations to prod DB
        if: github.ref == 'refs/heads/main'
        run: wrangler d1 migrations apply hello-db --remote
        working-directory: frontend
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
